title: Phuoc Dat Doan	
description: My Personal Pages
author: Phuoc Dat Doan
logo: /phuocddat.github.io/static/img/avatar.png
github: https://github.com/phuocddat
about: 

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: phuocddat
google_analytics: UA-102365232-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
